### PR TITLE
WIP: Administrative routes and unified _get and _post methods

### PR DESCRIPTION
**Pull request by pastewka**
This PR adds:
* Administrative routes (listing, adding and modifying users)

This PR cleans up:
* Unified _get and _post method that is called from the individual routes; reduced code dublication

### CODE REVIEW

**Comment by pastewka** [comment]
Hi @jotelha - can you help me with the tests here? I don't think I understand how they work.

**Comment by jotelha** [comment]
@pastewka the main issue here seems to be that "testuser" has no admin privileges within that testing container composition and hence no access to any of those admin routes, I am applying the necessary modifications.

**Comment by pastewka** [comment]
Sounds good and thank you
________________________________
Von: "Johannes L. Hörmann" ***@***.***>
Gesendet: Sonntag, 15. August 2021 14:47
An: IMTEK-Simulation/dtool-lookup-api
Cc: Lars Pastewka; Mention
Betreff: Re: [IMTEK-Simulation/dtool-lookup-api] WIP: Administrative routes and unified _get and _post methods (#10)

**Comment by jotelha** [comment]
Still needs a test for update_permissions, https://github.com/IMTEK-Simulation/dtool-lookup-api/blob/0aaf31ab6b8187a66dae3d44f56098ead81f79ab/tests/test_dtool_lookup_api_synchronous.py#L281-L302

**Pull request merged**
